name: Drupal Tests

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Install Psh CLI.
      - name: Install Psh CLI
        run: curl -sS https://platform.sh/cli/installer | php

      - name: Dump the latest staging DB
        run: ~/.platformsh/bin/platform --project=q3ocxrcgwdzfm --environment=Staging db:dump --gzip --file=db.sql.gz


      - name: Setup Lando
        uses: lando/setup-lando@v2
        with:
          lando-version: 3.14.0

      - name: Lando rebuild
        run: lando rebuild -y

      - name: Lando start
        run: lando start

      - name: check lando info
        run: lando info

      - name: Configure Database Connection
        run: |
          # Update settings.php with database credentials
          echo "<?php
          \$databases['default']['default'] = array(
            'database' => 'drupal10',
            'username' => 'drupal10',
            'password' => 'drupal10',
            'host' => 'database',
            'port' => '3306',
            'driver' => 'mysql',
            'prefix' => '',
          );
          \$settings['hash_salt'] = '6HhsaKMpNOs6lUs5rZcxRpnQ8XRqcR_QnCO2au9J5E6-Oo6SxJPJ5sUc1X1rKsDawrhVb9KP6Q';
          " > web/sites/default/settings.php

      - name: Validate Composer
        run: composer validate

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Composer Cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer Dependencies
        run: composer --no-interaction install --no-progress --prefer-dist --no-suggest --optimize-autoloader

      - name: Run drush site install Command
        run: |
          lando drush si --account-name=admin --account-pass=admin

      - name: Run drush cr Command
        run: lando drush cr

#      - name: Close tunnel
#        run: ~/.platformsh/bin/platform tunnel:close --all -y

      - name: Close lando
        run: lando stop
    env:
      PLATFORMSH_CLI_TOKEN: ${{ secrets.PLATFORMSH_CLI_TOKEN }}
